[package]
name = "fun-rougelike"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14" }
bevy_ecs_ldtk = { git = "https://github.com/Trouv/bevy_ecs_ldtk.git", version = "0.10.0" }
bevy-inspector-egui = "0.25"

